### ISSUE TITLE
Need more information

### ISSUE THREAD

**Issue by skumaresan** [nazar-pc/unicode-range-splitter#1]
Hi,

I am using mac os for my development. I just tried to use this project for splitting my fonts, however i am unable to run `docker` command. It would be helpful if you provide examples likes how to split fonts.

**Comment by nazar-pc** [comment]
This repository only contains examples about this project and assumes you have Docker installed on your machine already (I will add a note about this when get back to my desktop machine).

For macOS this should help you to install Docker itself: https://docs.docker.com/docker-for-mac/install/

**Comment by nazar-pc** [comment]
@skumaresan, did you get it working, can we close the issue?
